# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip:
    - uv-lock
    - cargo-fmt
    - cargo-deny
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: 278e5cffad3af72e94baa7f447ee9d4752ef43c7  # frozen: v0.9.15
    hooks:
      - id: tombi-format
        exclude: (Cargo|uv)\.lock
        args: ["--offline"]
  - repo: https://github.com/crate-ci/typos
    rev: f06b85043a5ab470afbb0a5592456e733243983a  # frozen: v1
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0397b68f6f88c024f1d2b355a9818779f6336d16  # frozen: 0.11.3
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c60c980e561ed3e73101667fe8365c609d19a438  # frozen: v0.15.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  # Copied from maturin repo
  - repo: local
    hooks:
      - id: cargo-fmt # rustup component add rustfmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-deny # cargo install --locked cargo-deny
        name: cargo deny
        entry: cargo deny --all-features check --
        language: system
        pass_filenames: false
