# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip:
    - uv-lock
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: 8af3b44ab8041f690f93557ed2aa129a8121161f  # frozen: v1.2.1
    hooks:
      - id: tombi-format
        exclude: (Cargo|uv)\.lock
        args: ["--offline"]
  - repo: https://github.com/crate-ci/typos
    rev: bee27e3a4fd1ea2111cf90ab89cd076c870fce14  # frozen: v1.48.0
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: b7359babf83a050dcd7bf892538f3df09c3d4ba6  # frozen: 0.11.29
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2700fd5671c633760d912769c041bfcde2b9a01b  # frozen: v0.15.22
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
