# https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - apt-get -y install rustup
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv run --frozen make BUILDDIR="$READTHEDOCS_OUTPUT" O="-T" -C docs html
