# https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain none --profile minimal
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - . "$HOME/.cargo/env" && uv run -v --frozen make BUILDDIR="$READTHEDOCS_OUTPUT" O="-T" -C docs html
