[package]
name = "bosing"
version = "0.0.0-dev"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bosing"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.89"
bspline = "1.1.0"
cached = "0.53.1"
float-cmp = "0.10.0"
hashbrown = { version = "0.14.5", features = ["rayon"] }
indoc = "2.0.5"
itertools = "0.13.0"
ndarray = { version = "0.16.1", features = ["rayon"] }
num = "0.4.3"
numpy = "0.22.0"
ordered-float = "4.4.0"
pulp = "0.18.22"
pyo3 = { version = "0.22.5", features = ["hashbrown", "anyhow"] }
rayon = "1.10.0"
thiserror = "1.0.64"

[dev-dependencies]
mockall = "0.13.0"
test-case = "3.3.1"
