[package]
name = "bosing"
version = "0.0.0-dev"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bosing"
crate-type = ["cdylib"]

[dependencies]
bspline = "1.1.0"
float-cmp = "0.9.0"
ndarray = "0.15.6"
num = "0.4.1"
numpy = "0.21.0"
pyo3 = "0.21.0"
