[package]
name = "bosing"
version = "0.0.0-dev"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bosing"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.82"
bspline = "1.1.0"
enum_dispatch = "0.3.13"
float-cmp = "0.9.0"
itertools = "0.12.1"
mimalloc = "0.1.39"
ndarray = "0.15.6"
num = "0.4.1"
numpy = "0.21.0"
ordered-float = "4.2.0"
pyo3 = "0.21.0"
