[workspace]
members = ["bosing-py"]

[workspace.package]
version = "0.0.0-dev"
rust-version = "1.82"
license = "MIT"
authors = ["Jiahao Yuan <kahojyun@icloud.com>"]

[package]
name = "bosing"
edition = "2021"
version.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1.0.93"
bspline = "1.1.0"
cached = "0.54.0"
float-cmp = "0.10.0"
hashbrown = { version = "0.14.5", features = ["rayon"] }
indoc = "2.0.5"
itertools = "0.13.0"
ndarray = { version = "0.16.1", features = ["rayon"] }
num = "0.4.3"
numpy = "0.22.1"
ordered-float = "4.5.0"
pulp = "0.19.5"
pyo3 = { version = "0.22.6", features = [
  "hashbrown",
  "anyhow",
  "generate-import-lib",
  "abi3-py39",
] }
rayon = "1.10.0"
thiserror = "2.0.3"

[dev-dependencies]
mockall = "0.13.0"
test-case = "3.3.1"

[workspace.lints.rust]
rust-2018-idioms = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
allow_attributes = "warn"
todo = "warn"
unwrap_used = "warn"

[lints]
workspace = true
