name: Build python

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wheel:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        arch: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install build
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build
    - name: Build wheel
      run: python -m build --wheel
      env:
        BUILD_TARGET_ARCH: ${{ matrix.arch }}
    - name: Repair macOS wheel
      if: startsWith(matrix.os, 'macos')
      run: |
        pip install delocate
        delocate-wheel -v dist/*.whl
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/*.whl

  wheel-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.17
      env:
        CIBW_BUILD: "*-manylinux_x86_64"
        CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux_2_28_x86_64
        CIBW_BEFORE_ALL_LINUX: dnf install -y dotnet-sdk-8.0
        CIBW_BUILD_FRONTEND: build
        CIBW_TEST_SKIP: "*"
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-manylinux
        path: wheelhouse/*.whl

  sdist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install build
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build
    - name: Build sdist
      run: python -m build --sdist
    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz